# Generated by Django 6.0.5 on 2026-06-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='hours_added',
            field=models.BooleanField(default=False),
        ),
    ]
