# Generated by Django 6.0.5 on 2026-06-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_registration_checked_in_registration_hours_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.CharField(default='Организация', max_length=255),
        ),
    ]
