# Generated by Django 6.0.5 on 2026-06-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_end_date_event_end_time_event_max_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AddField(
            model_name='event',
            name='manual_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Код для ручного ввода'),
        ),
        migrations.AddField(
            model_name='event',
            name='qr_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='QR-токен'),
        ),
    ]
